메인페이지 작업
MIC-TEAM/miccha-front pull request #5
Opened 2021-05-12 10:42 UTC by leemember

레이아웃 헤더 추가, 인디게이터 타이틀 등등 스타일 조정 완료했습니다.
아래로 넘어가는 버튼은 이번주내로 작업하도록 하겠습니다!

2021-05-12 12:05 UTC, devho813 requested changes
리뷰 코멘트로 작성했습니다! 확인해 주시면 감사하겠습니다 :)

2021-05-12 12:05 UTC, devho813 commented on src/pages/components/Header/index.tsx
> +export const HeaderWrap = styled.nav`
해당 컴포넌트 내에서 사용하는 styled component 라면 앞에 export 키워드는 제거해도 될 것 같습니다

2021-05-12 12:13 UTC, devho813 commented
package.json
yarn.lock
파일 충돌이 발생했습니다! main 브랜치 pull 한번 받고 PR 보내셔야할 것 같아요~

2021-05-12 14:19 UTC, kjs0165 commented
수고하셨습니다. 저도 차노님 의견을 듣고 배우는 중입니다.^^;

2021-05-12 15:11 UTC, leemember commented
⭐️ @devho813 @kjs0165 ⭐️

**코드리뷰 피드백 감사합니다! 반영 완료했습니다.**
- [x] components 폴더 src 하위 디렉토리로 이동
- [x] emotion / export 제거
- [x] 주석제거
- [x] yarn 적용

👉🏻 이 외에 main.css -> 동일한 디렉토리에 styles.css로 이름 변경후
import './styles.css' 로 불러오기는 next라 modules.css로 해야 가능하더라구요!
이거에 대한 의견 부탁드립니다!

<img width="1141" alt="스크린샷 2021-05-12 오후 11 58 58" src="https://user-images.githubusercontent.com/71499150/117997726-31577b00-b37e-11eb-849a-f11a3f151044.png">

<img width="499" alt="스크린샷 2021-05-12 오후 11 59 37" src="https://user-images.githubusercontent.com/71499150/117997901-5ea42900-b37e-11eb-8fc3-b54f8f34debe.png">

현재 작업된 화면단 입니다.

## 💻 남은 작업

- [ ] Bottom Button 클릭시 다음 섹션으로 스크롤링 (마지막 섹션은 클릭하면 맨 위로 이동)
- [ ] Bottom Button 위치 조정
- [ ] 화면단 줄였을 때 헤더부분 간격 조절하기
- [ ] '2주 무료 이용 시작' 버튼 클릭 시 start 페이지로 라우팅

2021-05-13 06:04 UTC, devho813 reviewed
ignoreBuildErrors를 true로 세팅하면 타입 검사 무시로 빌드시에 타입 오류 검출이 안될 것 같습니다..!
혹시 따로 설정하신 이유가 있을까요!?

2021-05-13 07:27 UTC, leemember commented
fullpage d.ts 모듈작업 토스 하겠습니다 ㅎㅎ.. 감사합니다! 🙌

2021-05-13 07:29 UTC, devho813 submitted a review, later dismissed

2021-05-13 07:42 UTC, merged

2021-05-13 08:07 UTC, kjs0165 commented
늦게확인햇습니다.^^;;