[mic-048] add: favicon 추가 & 메뉴바 탐색하기 스타일링 작업완료
MIC-TEAM/miccha-front pull request #57
Opened 2021-06-30 01:14 UTC by leemember

- Miccha 에 M을 본따 favicon 추가 했습니다.
- 헤더 nav 서브 메뉴 `탐색하기` 스타일링 작업 완료했습니다.

2021-06-30 15:03 UTC, devho813 requested changes
리뷰 코멘트 1개 남겼습니다~

2021-06-30 15:03 UTC, devho813 commented on src/styles/home_header.ts
> +    }
미디어 쿼리 적용 시, 공통 모듈로 만들어 놓은 facepaint 라이브러리를 사용해 보는 것이 어떨까요 :)

2021-07-01 07:27 UTC, leemember commented on src/styles/home_header.ts
> +    }
넵 감사합니다! 😃

2021-07-01 07:29 UTC, leemember commented
리뷰해 주신대로 반영했습니다! 감사합니다!

2021-07-01 08:57 UTC, devho813 approved these changes
고생하셨습니다!

2021-07-01 08:57 UTC, merged