[mic-052] fix : 무비 슬라이드 화살표 버튼 생성
MIC-TEAM/miccha-front pull request #61
Opened 2021-07-07 07:37 UTC by leemember

무비 슬라이드 화살표 버튼 생성했습니다! 확인 부탁드립니당 감사합니다 :)

2021-07-07 08:43 UTC, devho813 requested changes

2021-07-07 08:43 UTC, devho813 commented on src/components/home/MovieSlider.tsx
> -            <IoIosArrowBack style={{ color: '#fff', opacity: '80%' }} />
그럼 react-icons 라이브러리는 안 쓰게되는 건가요? 
안 쓰는 패키지는 제거해 주는 게 좋을 것 같습니다~ (import 포함하여)

2021-07-08 00:14 UTC, leemember commented on src/components/home/MovieSlider.tsx
> -            <IoIosArrowBack style={{ color: '#fff', opacity: '80%' }} />
맞습니다 ! 수정해서 반영하겠습니다 감사합니당! 👍🏻

2021-07-08 04:15 UTC, devho813 approved these changes
리뷰 완료하였습니다 고생하셨어요~

2021-07-08 04:15 UTC, merged