[mic-006] fix : main page Scrolling 작업완료
MIC-TEAM/miccha-front pull request #8
Opened 2021-05-14 15:11 UTC by leemember

코드리뷰 부탁드립니다 감사합니다 😄

2021-05-14 15:19 UTC, leemember commented
alt 속성값 변경했습니다. 앞으론 꼼꼼하게 보고 한 번에 푸시하도록 하겠습니다 😅

2021-05-15 05:06 UTC, devho813 requested changes

2021-05-15 06:48 UTC, leemember commented on src/pages/index.tsx
> +  fullpageApi: any
아~~ 이렇게 인터페이스 타입 정의하는 것은 처음 알았네용 😄 감사합니다 !!

2021-05-15 06:49 UTC, leemember commented
@devho813 
import ReactFullpage, { fullpageApi } from '@fullpage/react-fullpage'

type Props = {
  fullpageApi: fullpageApi
}

이렇게 하는거 맞나욥 ? 반영하여 푸시했습니다 감사합니다 :)

2021-05-15 09:57 UTC, devho813 approved these changes
넵 맞습니다! 고생하셨습니다~!

2021-05-15 09:57 UTC, merged